POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/jpesquetinif/yocto-jetson/poky/meta \
  /home/jpesquetinif/yocto-jetson/poky/meta-poky \
  /home/jpesquetinif/yocto-jetson/poky/meta-yocto-bsp \
  /home/jpesquetinif/yocto-jetson/meta-openembedded/meta-oe \
  /home/jpesquetinif/yocto-jetson/meta-openembedded/meta-python \
  /home/jpesquetinif/yocto-jetson/meta-openembedded/meta-networking \
  /home/jpesquetinif/yocto-jetson/meta-openembedded/meta-filesystems \
  /home/jpesquetinif/yocto-jetson/meta-virtualization \
  /home/jpesquetinif/yocto-jetson/meta-tegra \
  /home/jpesquetinif/yocto-jetson/meta-drc-assistant \
  "
