MACHINE = "jetson-nano-devkit"
DISTRO = "poky"

IMAGE_INSTALL:append = " openssh-sftp-server"

BB_NUMBER_THREADS = "4"
PARALLEL_MAKE = "-j4"

DL_DIR = "${TOPDIR}/../downloads"
SSTATE_DIR = "${TOPDIR}/../sstate-cache"

# Obligatorio para los binarios propietarios de NVIDIA
ACCEPT_NVIDIA_EULA = "1"