MACHINE = "jetson-nano-devkit"
DISTRO = "poky"

IMAGE_INSTALL:append = " openssh-sftp-server"

BB_NUMBER_THREADS = "4"
PARALLEL_MAKE = "-j4"

DL_DIR = "${TOPDIR}/../downloads"
SSTATE_DIR = "${TOPDIR}/../sstate-cache"

# Obligatorio para los binarios propietarios de NVIDIA
ACCEPT_NVIDIA_EULA = "1"

# Módulos USB gadget serial
KERNEL_MODULE_AUTOLOAD:append = " g_serial"
IMAGE_INSTALL:append = " kernel-modules"

# Activación automática de systemd-networkd
SYSTEMD_AUTO_ENABLE_pn-systemd = "enable"

# Systemd como init manager
DISTRO_FEATURES:append = " systemd virtualization"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

# Fix boot: forzar partición root correcta
KERNEL_ROOTSPEC = "root=/dev/mmcblk0p1 rw rootwait"

# Permitir login como root sin contraseña (debug/desarrollo)
EXTRA_IMAGE_FEATURES += "debug-tweaks"

# Deshabilitar getty en tty1 para que drc-assistant tome la consola
SYSTEMD_DEFAULT_TARGET = "multi-user.target"

# Espacio mínimo — expand-rootfs expande en primer boot
IMAGE_ROOTFS_EXTRA_SPACE = "2000000"

# AUTOREV solo en desarrollo
BB_SRCREV_POLICY = "cache"

CONF_VERSION = "2"
